# SPDX-License-Identifier: Apache-2.0

from .compile import compile, compile_contract
from .errors import RegistryProjectError, ResolutionError
from .merge import merge
from .parser import parse
from .project import (
    delete_project_document,
    load_project,
    save_project_document,
    write_merge_strategies,
)
from .registry import (
    collect_references,
    compose_strategies,
    create_composition,
    create_modifier,
    create_palette,
    create_template,
    get_registry_document,
    list_registry_entries,
    merge_registry,
    remove_registry_document,
    upsert_registry_document,
    validate_registry,
)
from .resolve import (
    resolve_aesthetic,
    resolve_composition,
    resolve_named_composition,
    resolve_palette,
    resolve_template,
)
from .strategies import derive_strategies
from .tokens import compile_design_tokens, to_css_variables
from .types import (
    CapabilityManifest,
    CompileResult,
    Criticality,
    CssVariableMap,
    DesignTokens,
    DocumentKind,
    Json,
    JsonObject,
    LoadedProject,
    LoweringAction,
    MergeStrategies,
    MergeStrategy,
    Registry,
    RegistryDiagnostic,
    RegistryDiagnosticCode,
    RegistryEntrySummary,
    RegistryKind,
    RegistryReference,
    ResolutionErrorKind,
    ValidationIssue,
    ValidationResult,
)
from .validator import Validator, create_validator

__all__ = [
    "CapabilityManifest",
    "CompileResult",
    "Criticality",
    "CssVariableMap",
    "DesignTokens",
    "DocumentKind",
    "Json",
    "JsonObject",
    "LoadedProject",
    "LoweringAction",
    "MergeStrategies",
    "MergeStrategy",
    "Registry",
    "RegistryDiagnostic",
    "RegistryDiagnosticCode",
    "RegistryEntrySummary",
    "RegistryKind",
    "RegistryProjectError",
    "RegistryReference",
    "ResolutionError",
    "ResolutionErrorKind",
    "ValidationIssue",
    "ValidationResult",
    "Validator",
    "collect_references",
    "compile",
    "compile_contract",
    "compile_design_tokens",
    "compose_strategies",
    "create_composition",
    "create_modifier",
    "create_palette",
    "create_template",
    "create_validator",
    "delete_project_document",
    "derive_strategies",
    "get_registry_document",
    "list_registry_entries",
    "load_project",
    "merge",
    "merge_registry",
    "parse",
    "remove_registry_document",
    "resolve_aesthetic",
    "resolve_composition",
    "resolve_named_composition",
    "resolve_palette",
    "resolve_template",
    "save_project_document",
    "to_css_variables",
    "upsert_registry_document",
    "validate_registry",
    "write_merge_strategies",
]
